{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1452.0 (24.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"base_transacoes\",\"data_inicial\",\"data_final\",\"moedas\",\"calendario\",\"transacoes\",\"getCotacoes\",\"cotacoes\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "base_transacoes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"C:\\Users\\lucas.rodrigues\\projetos\\youtube-20241111-git-github\\transacoes.xlsx\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "f00a1c37-0c21-477a-8cea-182d8b1c7c4c",
        "queryGroup": "Parâmetros"
      },
      {
        "name": "data_inicial",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": "#date(2024, 11, 1) meta [IsParameterQuery=true, Type=\"Date\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "c23e517c-ca15-48ee-8f32-62dd3ae11caf",
        "queryGroup": "Parâmetros"
      },
      {
        "name": "getCotacoes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    getCotacoes = (dataInicial as date, dataFinal as date, moeda as text, pagina as number) as table =>",
          "    let",
          "        url = \"https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata\",",
          "        endpoint = \"CotacaoMoedaPeriodo(moeda=@moeda,dataInicial=@dataInicial,dataFinalCotacao=@dataFinalCotacao)\",",
          "        query = [",
          "            #\"@moeda\" = \"'\" & moeda & \"'\",",
          "            #\"@dataInicial\" = \"'\" &  Date.ToText(dataInicial,\"MM-dd-yyyy\") & \"'\",",
          "            #\"@dataFinalCotacao\" = \"'\" & Date.ToText(dataFinal,\"MM-dd-yyyy\") & \"'\",",
          "            #\"$top\" = Number.ToText(100),",
          "            #\"$skip\" = Number.ToText((pagina-1)*100),",
          "            #\"$format\"= \"json\"",
          "        ],",
          "        request = Web.Contents(",
          "            url,",
          "            [ RelativePath = endpoint, Query = query ]",
          "        ),",
          "        response = Json.Document(request, 65001), ",
          "        lista = response[value] ",
          "    in",
          "        Table.FromRecords(lista), ",
          "",
          "    getCotacoesPaginacao = (dataInicial as date, dataFinal as date, moeda as text) as table =>",
          "    let",
          "        todasPaginas = List.Generate(",
          "            ( ) => [ pagina = 1, cotacao = try getCotacoes(dataInicial, dataFinal, moeda, pagina) otherwise null ],",
          "                each [cotacao] <> null and Table.RowCount([cotacao]) > 0,",
          "                each [ pagina = [pagina] + 1, cotacao = try getCotacoes( dataInicial, dataFinal, moeda, pagina ) otherwise null],",
          "                each [cotacao]",
          "        ) ",
          "    in",
          "        Table.AddColumn(Table.Combine(todasPaginas), \"Moeda\", each moeda, type text),",
          "",
          "    processaCotacoes = (dataInicial as date, dataFinal as date) as table =>",
          "    let",
          "        moedas = List.Select(moedas[Moeda], each _ <> \"BRL\"),",
          "",
          "        todasCotacoes = List.Accumulate(",
          "            moedas,",
          "            #table({},{}),",
          "            (s, c) => ",
          "            Table.Combine({s, getCotacoesPaginacao(dataInicial, dataFinal, c)})",
          "",
          "        ),",
          "",
          "        colunasSelecionadas = Table.SelectColumns(",
          "            todasCotacoes,",
          "            { \"Moeda\", \"dataHoraCotacao\", \"cotacaoCompra\", \"tipoBoletim\" }",
          "        ),",
          "",
          "        colunasRenomeadas = Table.RenameColumns(",
          "            colunasSelecionadas,",
          "            {",
          "                {\"dataHoraCotacao\", \"DataHora\"},",
          "                {\"cotacaoCompra\", \"Cotacao\"},",
          "                {\"tipoBoletim\", \"TipoBoletim\"}",
          "            }",
          "        ),",
          "",
          "        tipoAlterado = Table.TransformColumnTypes(",
          "            colunasRenomeadas,",
          "            {",
          "                {\"DataHora\", DateTime.Type},",
          "                {\"Cotacao\", Number.Type}, ",
          "                {\"TipoBoletim\", Text.Type}",
          "            }",
          "        ),",
          "",
          "        dataAdicionada = Table.AddColumn(",
          "            tipoAlterado,",
          "            \"Data\", ",
          "            each DateTime.Date([DataHora]),",
          "            type date",
          "        )",
          "",
          "    in",
          "        dataAdicionada   ",
          "",
          "in",
          "    processaCotacoes"
        ],
        "kind": "m",
        "lineageTag": "97f5bef5-b1d0-4883-ba1e-1c669d114dcb",
        "queryGroup": "Funções"
      },
      {
        "name": "data_final",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": "DateTime.Date(DateTime.LocalNow())",
        "kind": "m",
        "lineageTag": "d94dafd7-724e-4c1f-92a1-f56ec1e76d6e",
        "queryGroup": "Parâmetros"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Parâmetros"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Dimensões"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Fatos"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Funções"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_de42378a-0d75-45be-9d41-6095d1c93b85",
        "fromColumn": "Moeda",
        "fromTable": "transacoes",
        "toColumn": "Moeda",
        "toTable": "moedas"
      },
      {
        "name": "AutoDetected_40824b60-a54c-43a9-ba05-f8c13014e1b7",
        "fromColumn": "Moeda",
        "fromTable": "cotacoes",
        "toColumn": "Moeda",
        "toTable": "moedas"
      },
      {
        "name": "f5d0dd37-33d8-93fa-3c71-57c63b8af094",
        "fromColumn": "Data",
        "fromTable": "transacoes",
        "toColumn": "Data",
        "toTable": "calendario"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "moedas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Moeda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e3cb4e0-76d1-4fbb-9216-9ff5885d012d",
            "sourceColumn": "Moeda",
            "summarizeBy": "none"
          },
          {
            "name": "Nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f245184-9140-4704-b7f4-7a7bb1432fc8",
            "sourceColumn": "Nome",
            "summarizeBy": "none"
          },
          {
            "name": "Formato",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fdd6fe4e-0c2f-4141-ade8-21aa154d35d9",
            "sourceColumn": "Formato",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fc3d5119-53a7-4020-a790-d205868e3b15",
        "partitions": [
          {
            "name": "moedas",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    source = Table.FromRows(",
                "        {",
                "            {\"BRL\", \"Real brasileiro\", \"R$ #,##0.00;R$ #,##0.00;-\"},",
                "            {\"AUD\", \"Dólar australiano\", \"$ #,##0.00;$ #,##0.00;-\"},",
                "            {\"CAD\", \"Dólar canadense\", \"$ #,##0.00;$ #,##0.00;-\"},",
                "            {\"CHF\", \"Franco suíço\", \"Fr #,##0.00;Fr #,##0.00;-\"},",
                "            {\"DKK\", \"Coroa dinamarquesa\", \"kr #,##0.00;kr #,##0.00;-\"},",
                "            {\"EUR\", \"Euro\", \"€ #,##0.00;€ #,##0.00;-\"},",
                "            {\"GBP\", \"Libra Esterlina\", \"£ #,##0.00;£ #,##0.00;-\"},",
                "            {\"JPY\", \"Iene\", \"¥ #,##0;¥ #,##0;-\"},",
                "            {\"NOK\", \"Coroa norueguesa\", \"kr #,##0.00;kr #,##0.00;-\"},",
                "            {\"SEK\", \"Coroa sueca\", \"kr #,##0.00;kr #,##0.00;-\"},",
                "            {\"USD\", \"Dólar dos Estados Unidos\", \"$ #,##0.00;$ #,##0.00;-\"}",
                "        },",
                "        {\"Moeda\", \"Nome\", \"Formato\"}",
                "    ),",
                "    ",
                "    changedType = Table.TransformColumnTypes(",
                "        source,{",
                "            {\"Moeda\", type text}, ",
                "            {\"Nome\", type text}, ",
                "            {\"Formato\", type text}",
                "        }",
                "    )",
                "",
                "in",
                "    changedType"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "calendario",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "d91106db-931c-4fe4-9c79-afa1506f6e3b",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27795ecc-b6af-4162-9142-68bbc33d0537",
            "sourceColumn": "Ano",
            "summarizeBy": "none"
          },
          {
            "name": "MesAno",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "c83fbf23-bc5f-4599-a39e-7eb23327be18",
            "sortByColumn": "MesInicio",
            "sourceColumn": "MesAno",
            "summarizeBy": "none"
          },
          {
            "name": "MesInicio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "16f65676-d8ec-41bd-81a4-c045a914bede",
            "sourceColumn": "MesInicio",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6da0d994-9519-4968-b637-61c2873f9634",
        "partitions": [
          {
            "name": "calendario",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    dataInicial = data_inicial, ",
                "    dataFinal = data_final, ",
                "    ",
                "    datas = List.Dates(",
                "        dataInicial, ",
                "        Duration.Days(dataFinal-dataInicial) + 1, ",
                "        #duration(1, 0, 0, 0)",
                "    ),",
                "",
                "    calendario = #table(",
                "        type table[",
                "            Data = date,",
                "            Ano = Int64.Type,",
                "            MesAno = text,",
                "            MesInicio = date",
                "        ],",
                "        List.Transform(",
                "            datas,",
                "            each {",
                "                _,",
                "                Date.Year(_),",
                "                Date.ToText(_, [Format=\"MMM/yy\", Culture=\"pt-BR\"]),",
                "                Date.StartOfMonth(_)",
                "            }",
                "        )",
                "    )",
                "",
                "in",
                "    calendario"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "transacoes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9742582d-a7e9-4f0a-835f-adda402ed997",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "b553aa05-11d0-4505-b106-134d6c1ffdce",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3e46a60e-d02a-4df4-a4f8-a495710c11bd",
            "sourceColumn": "Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Moeda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3475251-27ff-4c73-a2ad-92bfc53a7743",
            "sourceColumn": "Moeda",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0ab4cadd-a46d-4ccb-85cb-b0e1585e9755",
        "partitions": [
          {
            "name": "transacoes",
            "mode": "import",
            "queryGroup": "Fatos",
            "source": {
              "expression": [
                "let",
                "    source = Excel.Workbook(",
                "        File.Contents(base_transacoes), ",
                "        true, ",
                "        null",
                "    ),",
                "    ",
                "    transacoes_Table = source{[Item=\"transacoes\",Kind=\"Table\"]}[Data],",
                "    ",
                "    datesRestricted = Table.SelectRows(",
                "        transacoes_Table, ",
                "        each [Data] >= data_inicial and [Data] <= data_final",
                "    )",
                "in",
                "    datesRestricted"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "cotacoes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Moeda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7328d037-928d-4100-a087-a553ba0634d6",
            "sourceColumn": "Moeda",
            "summarizeBy": "none"
          },
          {
            "name": "DataHora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "937a0b3c-4f6a-4161-b9ff-c28f5f8fe725",
            "sourceColumn": "DataHora",
            "summarizeBy": "none"
          },
          {
            "name": "Cotacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e9a9226c-386b-41a3-94d5-7b9abc09f349",
            "sourceColumn": "Cotacao",
            "summarizeBy": "sum"
          },
          {
            "name": "TipoBoletim",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e34674ad-d135-49f8-8f7c-b5b4bfa3dede",
            "sourceColumn": "TipoBoletim",
            "summarizeBy": "none"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "610c23c4-6cca-470f-b077-c636e3e3e274",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "db99b821-6bf4-4564-b80d-79265ed79762",
        "partitions": [
          {
            "name": "cotacoes",
            "mode": "import",
            "queryGroup": "Fatos",
            "source": {
              "expression": "getCotacoes(data_inicial, data_final)",
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}